# @see: https://marketplace.visualstudio.com/items?itemName=TomPollak.lazygit-vscode
os:
  edit: 'cursor {{filename}}'
  editAtLine: 'cursor --goto "{{filename}}:{{line}}"'
  editAtLineAndWait: 'cursor --goto "{{filename}}:{{line}}"'
  editInTerminal: true
  openDirInEditor: 'cursor {{dir}}'
promptToReturnFromSubprocess: false # removes "press enter to return to lazygit" popup

